controllers/JueganController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Juegan;
use app\models\JueganSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;

/**
 * JueganController implements the CRUD actions for Juegan model.
 */
class JueganController extends Controller
{
    /**
     * {@inheritdoc}
     */
     public $tc;
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Juegan models.
     * @return mixed
     */
    public function actionIndex()
    {
         $dataProvider = new ActiveDataProvider([
            'query' => Juegan::find(),
             'pagination'=>false,
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    
    }

    /**
     * Displays a single Juegan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Juegan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
//    public function actionCreate($id,$cod)
//    {
////        $model = new Juegan();
////        
////       
////        
////
////        if ($model->load(Yii::$app->request->post()) && $model->save()) {
////   
////        
////           $id=$model->cod_jugador;
////           $model->save();
////
////           return $this->redirect(array('juegan/puntos2', 'cod' => $model->cod_partido));
////        }
////
////        return $this->render('create', [
////            'model' => $model,
////            'id'=>$id,
////            'cod'=>$cod,
////         
////        ]);
//    }
//    NOS MOSTRARA LOS JUGADORES CON SUS IMAGENES EN LA VISTA ACTUALIZARJUEGAN pero 
public function actionActualizar($cod){
  $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,numero,puesto,imagen,j.cod_jugador,cod_juegan')
                    ->leftJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('estado=1')
          ->andWhere('agente_libre=0'),
          
            'pagination'=>false,
        ]);
        return $this->render("actualizarjuegan", [
                    'dataProvider' => $dataProvider,
                    'cod'=>$cod,
        ]);
    }
   
  
//     public function actionPuntos2($cod)
//    {
//$dataProvider = new \yii\data\SqlDataProvider([
//            'sql' => 'SELECT * '
//    . 'FROM jugadores j '
//    . 'WHERE j.cod_jugador NOT IN'
//    . '(SELECT j.cod_jugador FROM jugadores INNER JOIN juegan j ON jugadores.cod_jugador = j.cod_jugador WHERE j.cod_partido='.$cod.')'
//    . 'AND j.estado=1',
//          
//        ]);   
//
//        return $this->render('puntosjugador2', [
//            'dataProvider' => $dataProvider,
//            'cod'=>$cod,
//        ]);
//    }

 
    public function actionUpdate($codjugador,$cod)
    {
        $codjuegan= Juegan::find()
                ->select('cod_juegan')
                ->where('juegan.cod_jugador='.$codjugador)
                ->andWhere('cod_partido='.$cod)
                ->one();
        $model= $this->findModel($codjuegan);
       
       

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['juegan/actualizar', 'cod' => $cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    /**
     * Deletes an existing Juegan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Juegan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Juegan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Juegan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PartidosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Partidos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Jugadores;
use app\models\Juegan;
use yii\web\UploadedFile;

/**
 * PartidosController implements the CRUD actions for Partidos model.
 */
class PartidosController extends Controller {

    public function actionResultados() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido'),
            'pagination' => false,
        ]);
        return $this->render("resultados", [
                    "resultados" => $dataProvider,
        ]);
    }
     public function actionResultadosuser() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido'),
            'pagination' => false,
        ]);
        return $this->render("resultadosuser", [
                    "resultados" => $dataProvider,
        ]);
    }
     public function actionPartido($cod) {
      
        return $this->render("partido", [
                    "cod" => $cod,
        ]);
    }
     public function actionPartidouser($cod) {
      
        return $this->render("partidouser", [
                    "cod" => $cod,
        ]);
    }
    
    public function actionResultadospormes($mes=null) {
        if($mes==null){
            $mes = date('m');
        }
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido')
                    ->where("month(partidos.fecha)=$mes"),
            
            'pagination' => false,
        ]);
        return $this->render("resultadosmes", [
                    "mes"=>$mes,
                    "resultados" => $dataProvider,
        ]);
    }
     public function actionResultadospormesuser($mes=null) {
        if($mes==null){
            $mes = date('m');
        }
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido')
                    ->where("month(partidos.fecha)=$mes"),
            
            'pagination' => false,
        ]);
        return $this->render("resultadosmesuser", [
                    "mes"=>$mes,
                    "resultados" => $dataProvider,
        ]);
    }

    public function actionVistaindividual($cod) {
    
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Juegan::find()
                    ->select('
                    nombre,
                    cod_partido,
                    apellidos,
                    puntos_jugador,
                    rebotes_jugador,
                    asistencias_jugador,
                    robos,
                    minutos,
                    SUM(aciertos_jugador)/SUM(tiros_jugador)*100 AS TC,
                    SUM(t3_acertados)/SUM(t3_intentados)*100 T3,
                    SUM(minutos_jugador) minutos,
                    SUM(tl_acertados)/SUM(tl_intentados)*100 TL,
                    tapones')
                    ->innerJoin('jugadores', 'juegan.cod_jugador = jugadores.cod_jugador')
                    ->where('cod_partido='.$cod)
                    ->andWhere('puntos_jugador is not null')
                    ->groupBy('jugadores.cod_jugador'),
            'pagination' => false,
            'sort' => ['attributes' => ['nombre', 'apellidos', 'puntos_jugador', 'rebotes_jugador', 'asistencias_jugador','robos','minutos','TC', 'T3', 'TL','tapones']]
        ]);
        return $this->render("individuales", [
                    "resultados" => $dataProvider,
                     "cod"=>$cod
            
        ]);
    }
      public function actionVistaindividualuser($cod) {
    
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Juegan::find()
                    ->select('
                    nombre,
                    cod_partido,
                    apellidos,
                    puntos_jugador,
                    rebotes_jugador,
                    asistencias_jugador,
                    robos,
                    minutos,
                    SUM(aciertos_jugador)/SUM(tiros_jugador)*100 AS TC,
                    SUM(t3_acertados)/SUM(t3_intentados)*100 T3,
                    SUM(minutos_jugador) minutos,
                    SUM(tl_acertados)/SUM(tl_intentados)*100 TL,
                    tapones')
                    ->innerJoin('jugadores', 'juegan.cod_jugador = jugadores.cod_jugador')
                    ->where('cod_partido='.$cod)
                    ->andWhere('puntos_jugador is not null')
                    ->groupBy('jugadores.cod_jugador'),
            'pagination' => false,
            'sort' => ['attributes' => ['nombre', 'apellidos', 'puntos_jugador', 'rebotes_jugador', 'asistencias_jugador','robos','minutos','TC', 'T3', 'TL','tapones']]
        ]);
        return $this->render("individualesuser", [
                    "resultados" => $dataProvider,
                     "cod"=>$cod
            
        ]);
    }

    public function actionMaximos() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('month(fecha)fechames,nombre_rival,
                            SUM(j.puntos_jugador) AS puntos,
                            SUM(j.aciertos_jugador)/SUM(j.tiros_jugador)*100 AS TC,
                            SUM(j.t3_acertados)/SUM(j.t3_intentados)*100 AS T3,
                            SUM(j.tl_acertados)/SUM(j.tl_intentados)*100 AS TL')
                    ->innerJoin('juegan j', 'partidos.cod_partido=j.cod_partido')
                    ->groupBy('fechames'),
            'sort' => ['attributes' => ['fechames', 'puntos', 'TC', 'T3', 'TL']]
        ]);

        $dataProvider6 = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('month(fecha)fechames,nombre_rival,
                            SUM(j.puntos_jugador)puntos,
                            SUM(j.aciertos_jugador)/SUM(j.tiros_jugador)*100 AS TC,
                            SUM(j.t3_acertados)/SUM(j.t3_intentados)*100 AS T3,
                            SUM(j.tl_acertados)/SUM(j.tl_intentados)*100 AS TL')
                    ->innerJoin('juegan j', 'partidos.cod_partido=j.cod_partido')
                    ->groupBy('nombre_rival'),
            'pagination' => false,
            'sort' => ['attributes' => ['nombre_rival', 'puntos', 'TC', 'T3', 'TL']]
        ]);

        return $this->render("globales", [
                    "resultados" => $dataProvider,
                    "resultados6" => $dataProvider6,
//                    "resultados9" => $dataProvider9,
        ]);
    }
 

    public function actionLideres() {
        $dataProvider2 = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,
                            avg(puntos_jugador) puntos')
                    ->innerJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('jugadores.estado=1')
                    ->groupBy('jugadores.cod_jugador')
                    ->orderBy(['puntos' => SORT_DESC])
                    ->limit(1),
            'pagination' => false
        ]);
        $dataProvider3 = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,
                            avg(rebotes_jugador) rebotes')
                    ->innerJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('jugadores.estado=1')
                    ->groupBy('jugadores.cod_jugador')
                    ->orderBy(['rebotes' => SORT_DESC])
                    ->limit(1),
            'pagination' => false
        ]);
        $dataProvider4 = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,
                            avg(asistencias_jugador) asistencias')
                    ->innerJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('jugadores.estado=1')
                    ->groupBy('jugadores.cod_jugador')
                    ->orderBy(['asistencias' => SORT_DESC])
                    ->limit(1),
            'pagination' => false
        ]);

views/juegan/_actualizarjugador.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


<div id="cartas" class="col-lg-6">

          <div id="subcartas3" class="col-lg-1">
               <h1>  <?php
         echo  $model['numero'];
          ?></h1>
                 <?php
         echo '<p>' . $model['puesto'].'</p>';
          ?>
                 </div>
    
    <div id="subcartas" class="col-lg-5">
      
        <?php
 
               echo Html::img('@web/img/'.$model['nombre'].'.png');
        ?>
    </div>
    <div id="subcartas2" class="col-lg-6"style="display: flex;flex-direction: column;flex-wrap: wrap;align-items: flex-end;">
        <?php
      
 

        echo '<h1>' . $model['nombre'].' '.$model['apellidos'].'</h1>';
     
        ?>
        <?= Html::a('Añadir estadísticas', ['juegan/update', 'codjugador' => $model->cod_jugador,'cod' => $cod], ['class' => 'btn']) ?>
    </div>

    
    </div>

views/juegan/actualizarjuegan.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \yii\widgets\ListView;
use yii\debug\models\timeline\DataProvider;

/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="juegan-create">
    <div class="container">
 <h1 id="tituloañadir"><?= Html::a('volver atrás', ['partidos/update', 'id' => $cod],['class'=>'btn']) ?>AÑADIR PUNTOS<?= Html::a('finalizar', ['partidos/resultados'], ['class' => 'btn']) ?></h1>
 

<!-- HACEMOS EL LISTVIEW EN EL QUE LE PASAMOS EL CODIGO DEOL PARTIDO0 EN ESPECIFICO-->

<?= ListView::widget([
    'dataProvider'=>$dataProvider,
    'id'=>'prueba',
    'itemView'=>'_actualizarjugador',
    'viewParams'=>['cod'=>$cod],
]);
      
  ?>


    </div>
    </div>

views/juegan/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="juegan-create">

    <h1></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'id'=>$id,
        'cod'=>$cod,
       
        
    ]) ?>

</div>

views/juegan/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Juegans';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
<div class="juegan-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Juegan', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            

           
            'cod_jugador',
            'cod_partido',
            'puntos_jugador',
            'asistencias_jugador',
            'rebotes_jugador',
            'robos',
            'tiros_jugador',
            'aciertos_jugador',
            't3_intentados',
            't3_acertados',
            'tl_intentados',
            'tl_acertados',
            'minutos_jugador',
            //'tapones',
            //'+/-',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>
    </div>

views/juegan/update.php
<?php

use kartik\form\ActiveForm;
use kartik\builder\Form;
use yii\helpers\Html;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use app\models\Jugadores;
use app\models\Entrenamientos;

/* @var $this yii\web\View */
/* @var $model app\models\Juegan */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container">
<div class="juegan-form">
  <h1 id="tituloform">AÑADIR ESTADISTICAS</h1>
  
<?php
$codigo=$model->getOldAttribute('cod_jugador');
  $jugadores = Jugadores::find()
        ->select('nombre,apellidos')
        ->Where("cod_jugador=" . $codigo)
        ->one();
$array = [
    ['id' => $model->cod_jugador, 'data' =>$model->nombre ],
   
];

   $form = ActiveForm::begin(['type' => ActiveForm::TYPE_VERTICAL]);
//   esto es para coger el codigo del jugador, si se borra el cod es null
  

   echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 2,
            'attributes' => [
                'cod_jugador' => ['label' => 'Jugador', 'type' => Form::INPUT_TEXT, 'options' => ['readonly'=>true,'placeholder'=>$jugadores->nombre.' '.$jugadores->apellidos]],
                'cod_partido' => ['label' => 'Partido', 'type' => Form::INPUT_TEXT, 'options' => ['readonly'=>true]],
               
            ]
        ]);
    echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 3,
            'attributes' => [
                'puntos_jugador' => ['label' => 'Puntos', 'type' => Form::INPUT_TEXT,],
                  'rebotes_jugador' => ['label' => 'Rebotes', 'type' => Form::INPUT_TEXT,],
                  'asistencias_jugador' => ['label' => 'Asistencias', 'type' => Form::INPUT_TEXT,],
               
            ]
        ]);
       echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 3,
            'attributes' => [
                'minutos_jugador' => ['label' => 'Minutos jugados', 'type' => Form::INPUT_TEXT,],
                  'robos' => ['label' => 'Robos', 'type' => Form::INPUT_TEXT,],
                  'tapones' => ['label' => 'Tapones', 'type' => Form::INPUT_TEXT,],
               
            ]
        ]);
         echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 2,
            'attributes' => [
                'tiros_jugador' => ['label' => 'Tiros de campo', 'type' => Form::INPUT_TEXT,],
                  'aciertos_jugador' => ['label' => 'Tiros acertados', 'type' => Form::INPUT_TEXT,],
               
            ]
        ]);
           echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 2,
            'attributes' => [
                't3_intentados' => ['label' => 'Triples intentados', 'type' => Form::INPUT_TEXT,],
                  't3_acertados' => ['label' => 'Triples acertados', 'type' => Form::INPUT_TEXT,],
           
               
            ]
        ]);
             echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 2,
            'attributes' => [
                'tl_intentados' => ['label' => 'Tiros libres intentados', 'type' => Form::INPUT_TEXT,],
                  'tl_acertados' => ['label' => 'Tiros libres acertados', 'type' => Form::INPUT_TEXT,],
           
               
            ]
        ]);

   echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 1,
            'attributes' => [
                '' => [
                    'type' => Form::INPUT_RAW,
                    'value' => '<div style="  text-align: right;margin-top: 6px;padding-top: 20px;padding-bottom: 52px;margin-right: -30px;padding-right: 30px;background-color: #EDEDED;margin-left: -30px;">' .
                    Html::resetButton('Reset', ['class' => 'btn', 'id' => 'btnf']) . ' ' .
                    Html::submitButton('Añadir', ['class' => 'btn', 'id' => 'btnf']) .
                    '</div>'
                ],
            ]
        ]);

    

    ActiveForm::end(); ?>

</div>
    </div>

views/juegan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = $model->cod_juegan;
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="juegan-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->cod_juegan], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->cod_juegan], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'cod_juegan',
            'cod_jugador',
            'cod_partido',
            'puntos_jugador',
            'asistencias_jugador',
            'rebotes_jugador',
            'robos',
            'tiros_jugador',
            'aciertos_jugador',
            't3_intentados',
            't3_acertados',
            'tl_intentados',
            'tl_acertados',
            'minutos_jugador',
            'tapones',
            '+/-',
        ],
    ]) ?>

</div>