models/Contratos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "contratos".
 *
 * @property int $cod_contrato
 * @property int $año1
 * @property int|null $año2
 * @property int|null $año3
 * @property int|null $opcion_jugador
 * @property string|null $fecha_inicio
 * @property string|null $fecha_fin
 * @property int|null $clausula_antitraspaso
 * @property int|null $cod_jugador
 *
 * @property Jugadores $codJugador
 */
class Contratos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
     public $salario;
     public $margens;
     public $margeni;
     public $nombre;
     public $apellidos;

    public static function tableName()
    {
        return 'contratos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['año1'], 'required'],
            [['opcion_jugador', 'clausula_antitraspaso', 'cod_jugador'], 'integer'],
            [['fecha_inicio', 'fecha_fin'], 'safe'],
//            [['cod_jugador'], 'exist', 'skipOnError' => true, 'targetClass' => Jugadores::className(), 'targetAttribute' => ['cod_jugador' => 'cod_jugador']],
            [['año1', 'año2', 'año3'],'integer','max' => 50000000, 'min' => 0]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cod_contrato' => 'Cod Contrato',
            'año1' => 'Año1',
            'año2' => 'Año2',
            'año3' => 'Año3',
            'opcion_jugador' => 'Opción Jugador',
            'fecha_inicio' => 'Fecha Inicio',
            'fecha_fin' => 'Fecha Fin',
            'clausula_antitraspaso' => 'Cláusula Antitraspaso',
            'cod_jugador' => 'Cod Jugador',
        ];
    }

    /**
     * Gets query for [[CodJugador]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodJugador()
    {
        return $this->hasOne(Jugadores::className(), ['cod_jugador' => 'cod_jugador']);
    }
}

controllers/ContratosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Contratos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ContratosController implements the CRUD actions for Contratos model.
 */
class ContratosController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function actionContratos() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            cod_contrato,
                            nombre,
                            apellidos,
                            año1,
                            año2,
                            año3,
                            clausula_antitraspaso,
                            opcion_jugador,
                            fecha_inicio,
                            fecha_fin')
                    ->innerJoin('jugadores j', 'contratos.cod_jugador=j.cod_jugador')
                    ->where('(estado=1 AND j.agente_libre=0)OR(agente_libre=0 AND estado IS NULL)'),
            'sort' => ['attributes' => ['nombre', 'salario', 'fecha_inicio', 'fecha_fin', 'año1', 'año2', 'año3', 'clausula_antitraspaso', 'opcion_jugador']]
        ]);
        return $this->render("resultados", [
                    "resultados" => $dataProvider,
        ]);
    }

    public function actionRenovaciones() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            cod_contrato,
                           j.cod_jugador,
                            nombre,
                            apellidos,
                            año1,
                            año2,
                            año3,
                            clausula_antitraspaso,
                            fecha_inicio,
                            fecha_fin')
                    ->innerJoin('jugadores j', 'contratos.cod_jugador=j.cod_jugador')
                    ->where('estado=1')
                    ->andWhere('año2 is null'),
            'sort' => ['attributes' => ['nombre', 'salario', 'fecha_inicio', 'fecha_fin']]
        ]);
        return $this->render("renovaciones", [
                    "resultados" => $dataProvider,
        ]);
    }

    public function actionMargen() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            sum(año1) AS salario')->scalar()
//                          
        ]);
        $dataProvideraño2 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            sum(año2) AS salario')->scalar()
//                          
        ]);
        $dataProvideraño3 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            sum(año3) AS salario')->scalar()
//                          
        ]);
        $dataProvider2 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            (109140000-sum(año1)) AS "margens"')->scalar()
//                          
        ]);
        $dataProvider3 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('
                            (132637000-sum(año1)) AS "margeni"')->scalar()
//                          
        ]);
        $dataProvider4 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
//                  SELECT j.nombre,j.apellidos FROM contratos c INNER JOIN jugadores j ON c.cod_jugador = j.cod_jugador WHERE c.año1=(SELECT MAX(c.año1) FROM contratos c)
                    ->select('nombre')
                    ->innerJoin("jugadores", "jugadores.cod_jugador=contratos.cod_jugador")
                    ->where("año1=(select max(año1) from contratos)")
                    ->scalar()
//                          
        ]);
         $dataProvider7 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
//                  SELECT j.nombre,j.apellidos FROM contratos c INNER JOIN jugadores j ON c.cod_jugador = j.cod_jugador WHERE c.año1=(SELECT MAX(c.año1) FROM contratos c)
                    ->select('apellidos')
                    ->innerJoin("jugadores", "jugadores.cod_jugador=contratos.cod_jugador")
                    ->where("año1=(select max(año1) from contratos)")
                    ->scalar()
//                          
        ]);
        $dataProvider5 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
//                  SELECT j.nombre,j.apellidos FROM contratos c INNER JOIN jugadores j ON c.cod_jugador = j.cod_jugador WHERE c.año1=(SELECT MAX(c.año1) FROM contratos c)
                    ->select('apellidos')
                    ->innerJoin("jugadores", "jugadores.cod_jugador=contratos.cod_jugador")
                    ->where("año1=(select max(año1) from contratos)")
                    ->scalar()
//                          
        ]);
        

        $dataProvider6 = new ActiveDataProvider([
            'query' => \app\models\Contratos::find()
                    ->select('max(año1)')
                    ->scalar()
//                          
        ]);
        return $this->render("vistamargen", [
                    "margen" => $dataProvider,
                    "margen2" => $dataProvider2,
                    "margen3" => $dataProvider3,
                    "margen4" => $dataProvider4,
                    "margen5" => $dataProvider5,
                    "margen6" => $dataProvider6,
             "margen9" => $dataProvider7,
                    "margen7" => $dataProvideraño2,
                    "margen8" => $dataProvideraño3,
        ]);
    }

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Contratos models.
     * @return mixed
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Contratos::find(),
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Contratos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Contratos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($cod) {
        $model = new Contratos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('../contratos/contratos');
        }

        return $this->render('create', [
                    'model' => $model,
                    'cod' => $cod,
        ]);
    }

    public function actionCreate_1() {
        $model = new Contratos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['contratos']);
        }

        return $this->render('create_1', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Contratos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['contratos']);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Contratos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['contratos']);
    }

    /**
     * Finds the Contratos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Contratos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Contratos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/contratos/_form.php
<?php

use kartik\form\ActiveForm;
use kartik\builder\Form;
use yii\helpers\Html;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use app\models\Jugadores;
use app\models\Entrenamientos;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form">
    <div class="container">
        <h1 id="tituloform">CONTRATOS</h1>


        <?php
//          $jugadores = Jugadores::find()
//                
//                  ->leftJoin("contratos","jugadores.cod_jugador=contratos.cod_jugador")
//                  ->where('agente_libre=0')
//                  ->andWhere("estado=1")
//                  ->andWhere("año1 is  null")
//                ->all();
//
//        foreach ($jugadores as &$jugador) {
//            $jugador->nombre = $jugador->nombre . ' ' . $jugador->apellidos;
//        }
//
//        $items = ArrayHelper::map($jugadores, 'cod_jugador', 'nombre');
        
//        para coger el nombre del jugador en especifico
        $jugador1 = Jugadores::find()
                ->select('nombre')
                ->where('cod_jugador=' . $cod)
                ->one();



        $array = [
            ['id' => $cod, 'data' => $jugador1->nombre],
        ];
        $result = ArrayHelper::map($array, 'id', 'data');
        $form = ActiveForm::begin(['type' => ActiveForm::TYPE_VERTICAL]);
      
        echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 3,
            'attributes' => [
                 'cod_jugador' => ['label' => 'Jugador', 'type' => Form::INPUT_DROPDOWN_LIST, 'items' => $result],
                 'clausula_antitraspaso' => ['label' => 'Cláusula antitraspaso', 'type' => Form::INPUT_RADIO_LIST,'items'=>[true=>'sí', false=>'no'], 'options'=>['inline'=>false] ],
                'opcion_jugador' => ['label' => 'Opción de jugador', 'type' => Form::INPUT_RADIO_LIST,'items'=>[true=>'sí', false=>'no'], 'options'=>['inline'=>false]],
            ]
        ]);
        echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 3,
            'attributes' => [
                'año1' => ['label' => 'Salario Año 1', 'type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Salario del jugador en el primer año']],
                'año2' => ['label' => 'Salario Año 2', 'type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Salario del jugador en el segundo año']],
                'año3' => ['label' => 'Salario Año 3', 'type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Salario del jugador en el tercer año']],
            ]
        ]);
       
      
       echo $form->field($model, 'fecha_inicio')->widget(DateControl::classname(), [
    'type' => 'date',
    'ajaxConversion' => true,
    'autoWidget' => true,
      
    'widgetClass' => '',
    'displayFormat' => 'dd-MM-yyyy',
    'saveFormat' => 'php:Y-m-d',
    'saveTimezone' => 'Europe/Brussels',
    'displayTimezone' => 'Europe/Brussels',
   
     'widgetOptions' => [
        'pluginOptions' => [
          
            'autoclose' => true,
            
        ]
    ],
    
    'language' => 'es'
]);
        
       echo $form->field($model, 'fecha_fin')->widget(DateControl::classname(), [
    'type' => 'date',
    'ajaxConversion' => true,
    'autoWidget' => true,
    'widgetClass' => '',
    'displayFormat' => 'dd-MM-yyyy',
    'saveFormat' => 'php:Y-m-d',
    'saveTimezone' => 'Europe/Brussels',
    'displayTimezone' => 'Europe/Brussels',
   
    'widgetOptions' => [
        'pluginOptions' => [
            'autoclose' => true,
            
        ]
    ],
    'language' => 'es'
]);
         echo '<br>';
         echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 1,
            'attributes' => [
                '' => [
                    'type' => Form::INPUT_RAW,
                    'value' => '<div style="  text-align: right;margin-top: 6px;padding-top: 20px;padding-bottom: 52px;margin-right: -30px;padding-right: 30px;background-color: #EDEDED;margin-left: -30px;">' .
                   Html::resetButton('Borrar', ['class' => 'btn', 'id' => 'btnf']) . ' ' .
                    Html::submitButton('Confirmar', ['class' => 'btn', 'id' => 'btnf']) .
                    '</div>'
                ],
            ]
        ]);
        ?>


    </div>

<?php ActiveForm::end(); ?>

</div>
</div>

views/contratos/_form_1.php
<?php

use kartik\form\ActiveForm;
use kartik\builder\Form;
use yii\helpers\Html;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use app\models\Jugadores;
use app\models\Entrenamientos;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form">
    <div class="container">
        <h1 id="tituloform">CONTRATOS</h1>


        <?php
        $jugadores = Jugadores::find()
                ->leftJoin("contratos", "jugadores.cod_jugador=contratos.cod_jugador")
                ->where('agente_libre=0')
                ->andWhere("estado=1")
                ->andWhere("año1 is  null")
                ->all();

        foreach ($jugadores as &$jugador) {
            $jugador->nombre = $jugador->nombre . ' ' . $jugador->apellidos;
        }

        $items = ArrayHelper::map($jugadores, 'cod_jugador', 'nombre');
        $form = ActiveForm::begin(['type' => ActiveForm::TYPE_VERTICAL]);

        echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 3,
            'attributes' => [
                'cod_jugador' => ['label' => 'Jugador', 'type' => Form::INPUT_DROPDOWN_LIST, 'items' => $items],
                'clausula_antitraspaso' => ['label' => 'Cláusula antitraspaso', 'type' => Form::INPUT_RADIO_LIST, 'items' => [true => 'sí', false => 'no'], 'options' => ['inline' => false]],
                'opcion_jugador' => ['label' => 'Opción de jugador', 'type' => Form::INPUT_RADIO_LIST, 'items' => [true => 'sí', false => 'no'], 'options' => ['inline' => false]],
            ]
        ]);
        echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 3,
            'attributes' => [
                'año1' => ['label' => 'Salario Año 1', 'type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Salario del jugador en el primer año']],
                'año2' => ['label' => 'Salario Año 2', 'type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Salario del jugador en el segundo año']],
                'año3' => ['label' => 'Salario Año 3', 'type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Salario del jugador en el tercer año']],
            ]
        ]);

        echo $form->field($model, 'fecha_inicio')->widget(DateControl::classname(), [
            'type' => 'date',
            'ajaxConversion' => true,
            'autoWidget' => true,
            'widgetClass' => '',
            'displayFormat' => 'dd-MM-yyyy',
            'saveFormat' => 'php:Y-m-d',
            'saveTimezone' => 'Europe/Brussels',
            'displayTimezone' => 'Europe/Brussels',
            'widgetOptions' => [
                'pluginOptions' => [
                    'endDate' => date('d-m-Y', strtotime('+60 months')),
                    'startDate' => date('d-m-Y', strtotime('-60 months')),
                    'autoclose' => true,
                ]
            ],
            'language' => 'es'
        ]);
        echo '<br>';
        echo $form->field($model, 'fecha_fin')->widget(DateControl::classname(), [
            'type' => 'date',
            'ajaxConversion' => true,
            'autoWidget' => true,
            'widgetClass' => '',
            'displayFormat' => 'dd-MM-yyyy',
            'saveFormat' => 'php:Y-m-d',
            'saveTimezone' => 'Europe/Brussels',
            'displayTimezone' => 'Europe/Brussels',
            'widgetOptions' => [
                'pluginOptions' => [
                    'endDate' => date('d-m-Y', strtotime('+60 months')),
                    'startDate' => date('d-m-Y', strtotime('-60 months')),
                    'autoclose' => true,
                ]
            ],
            'language' => 'es'
        ]);
        echo '<br>';
        echo Form::widget([
            'model' => $model,
            'form' => $form,
            'columns' => 1,
            'attributes' => [
                '' => [
                    'type' => Form::INPUT_RAW,
                    'value' => '<div style="  text-align: right;margin-top: 6px;padding-top: 20px;padding-bottom: 52px;margin-right: -30px;padding-right: 30px;background-color: #EDEDED;margin-left: -30px;">' .
                    Html::resetButton('Borrar', ['class' => 'btn', 'id' => 'btnf']) . ' ' .
                    Html::submitButton('Confirmar', ['class' => 'btn', 'id' => 'btnf']) .
                    '</div>'
                ],
            ]
        ]);
        ?>


    </div>

<?php ActiveForm::end(); ?>

</div>
</div>

views/contratos/renovaciones.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\DataColumn;
use yii\helpers\Url;
use kartik\export\ExportMenu;

$this->title = 'CONTRATOS';
$this->params['breadcrumbs'][] = $this->title;
?>
<script src="../js/jquery.js"></script>
<div class="jugadores-index">
    <div class="container">
         <?php
        if (Yii::$app->user->identity->admin) {
            ?>
        
        <h1 id="titulorenovaciones">  <?=
        ExportMenu::widget([
            'dataProvider' => $resultados,
            //usamos esto para poder concatenar las columnas.
            'columns' => [
                [
                    'attribute' => 'nombre',
                    'format' => 'html',
                    'label' => 'JUGADOR',
                    'value' => function ($model) {

                        return Html::img('../../web/img/' . $model->nombre . '.png',
                                        ['width' => '60px']) . '' . $model->nombre . ' ' . $model->apellidos;
                    },
                ],
                [
                    'label' => 'AÑO1',
                    'value' => function ($model) {
                        return number_format($model->año1) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO2',
                    'value' => function ($model) {
                        return number_format($model->año2) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO3',
                    'value' => function ($model) {
                        return number_format($model->año3) . ' $';
                    }
                ],
                    [
                    'label' => 'cláusula antitraspaso',
                    'attribute' => 'clausula_antitraspaso',
                    'value' => function ($model) {
                        if ($model->clausula_antitraspaso == 0) {
                            return 'NO';
                        } else {
                            return 'SI';
                        }
                    }
                ],
                [
                    'attribute' => 'fecha_inicio',
                    'label' => 'fecha de inicio ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_inicio));
                    }
                ],
                [
                    'attribute' => 'fecha_fin',
                    'label' => 'fecha de fin ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_fin));
                    }
                ],
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{renovar}',
                    'buttons' => [
                        'renovar' => function ($url, $model) {
                            $url = Url::to(['contratos/update', 'id' => $model->cod_jugador]);
                            return Html::a('<span class="glyphicon glyphicon-briefcase"></span>', $url, ['title' => 'Renovar']);
                        },
                    ],
                ],
            ]
        ]);?>Renovaciones</h1>

        <?=
     GridView::widget([
            'dataProvider' => $resultados,
            //usamos esto para poder concatenar las columnas.
            'columns' => [
                [
                    'attribute' => 'nombre',
                    'format' => 'html',
                    'label' => 'JUGADOR',
                    'value' => function ($model) {

                        return Html::img('../../web/img/' . $model->nombre . '.png',
                                        ['width' => '60px']) . '' . $model->nombre . ' ' . $model->apellidos;
                    },
                ],
                [
                    'label' => 'AÑO1',
                    'value' => function ($model) {
                        return number_format($model->año1) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO2',
                    'value' => function ($model) {
                        return number_format($model->año2) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO3',
                    'value' => function ($model) {
                        return number_format($model->año3) . ' $';
                    }
                ],
                  [
                    'label' => 'cláusula antitraspaso',
                    'attribute' => 'clausula_antitraspaso',
                    'value' => function ($model) {
                        if ($model->clausula_antitraspaso == 0) {
                            return 'NO';
                        } else {
                            return 'SI';
                        }
                    }
                ],
                [
                    'attribute' => 'fecha_inicio',
                    'label' => 'fecha de inicio ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_inicio));
                    }
                ],
                [
                    'attribute' => 'fecha_fin',
                    'label' => 'fecha de fin ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_fin));
                    }
                ],
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{renovar}',
                    'buttons' => [
                        'renovar' => function ($url, $model) {
//                            $url = Url::to(['contratos/update', 'id' => $model->cod_jugador]);
                            return Html::a('<span class="glyphicon glyphicon-briefcase"></span>',['contratos/update', 'id' => $model->cod_jugador], ['title' => 'Renovar']);
                          
                        },
                    ],
                ],
            ]
        ]);
        ?>
           <?php
        } else {
            ?>
<h1 id="titulorenovaciones">  <?=
        ExportMenu::widget([
            'dataProvider' => $resultados,
            //usamos esto para poder concatenar las columnas.
            'columns' => [
                [
                    'attribute' => 'nombre',
                    'format' => 'html',
                    'label' => 'JUGADOR',
                    'value' => function ($model) {

                        return Html::img('../../web/img/' . $model->nombre . '.png',
                                        ['width' => '60px']) . '' . $model->nombre . ' ' . $model->apellidos;
                    },
                ],
                [
                    'label' => 'AÑO1',
                    'value' => function ($model) {
                        return number_format($model->año1) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO2',
                    'value' => function ($model) {
                        return number_format($model->año2) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO3',
                    'value' => function ($model) {
                        return number_format($model->año3) . ' $';
                    }
                ],
                    [
                    'label' => 'clausula antitraspaso',
                    'attribute' => 'clausula_antitraspaso',
                    'value' => function ($model) {
                        if ($model->clausula_antitraspaso == 0) {
                            return 'NO';
                        } else {
                            return 'SI';
                        }
                    }
                ],
                [
                    'attribute' => 'fecha_inicio',
                    'label' => 'fecha de inicio ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_inicio));
                    }
                ],
                [
                    'attribute' => 'fecha_fin',
                    'label' => 'fecha de fin ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_fin));
                    }
                ],
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{renovar}',
                    'buttons' => [
                        'renovar' => function ($url, $model) {
                            $url = Url::to(['contratos/update', 'id' => $model->cod_jugador]);
                            return Html::a('<span class="glyphicon glyphicon-briefcase"></span>', $url, ['title' => 'Renovar']);
                        },
                    ],
                ],
            ]
        ]);?>Renovaciones</h1>

        <?=
     GridView::widget([
            'dataProvider' => $resultados,
            //usamos esto para poder concatenar las columnas.
            'columns' => [
                [
                    'attribute' => 'nombre',
                    'format' => 'html',
                    'label' => 'JUGADOR',
                    'value' => function ($model) {

                        return Html::img('../../web/img/' . $model->nombre . '.png',
                                        ['width' => '60px']) . '' . $model->nombre . ' ' . $model->apellidos;
                    },
                ],
                [
                    'label' => 'AÑO1',
                    'value' => function ($model) {
                        return number_format($model->año1) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO2',
                    'value' => function ($model) {
                        return number_format($model->año2) . ' $';
                    }
                ],
                [
                    'label' => 'AÑO3',
                    'value' => function ($model) {
                        return number_format($model->año3) . ' $';
                    }
                ],
                  [
                    'label' => 'clausula antitraspaso',
                    'attribute' => 'clausula_antitraspaso',
                    'value' => function ($model) {
                        if ($model->clausula_antitraspaso == 0) {
                            return 'NO';
                        } else {
                            return 'SI';
                        }
                    }
                ],
                [
                    'attribute' => 'fecha_inicio',
                    'label' => 'fecha de inicio ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_inicio));
                    }
                ],
                [
                    'attribute' => 'fecha_fin',
                    'label' => 'fecha de fin ',
                    'value' => function ($model) {
                        return date("d-m-Y", strtotime($model->fecha_fin));
                    }
                ],
              
            ]
        ]);
                 }
        ?>
 
    </div>
</div>

<script>
    $('table td:first-child').css('text-align', 'initial')

</script>