controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use kartik\mpdf\Pdf;
use app\models\FormRegister;
use app\models\Users;
use yii\widgets\ActiveForm;

class SiteController extends Controller {

    private function randKey($str = '', $long = 0) {
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str) - 1;
        for ($x = 0; $x < $long; $x++) {
            $key .= $str[rand($start, $limit)];
        }
        return $key;
    }

    public function actionConfirm() {
        $table = new Users;
        if (Yii::$app->request->get()) {

            //Obtenemos el valor de los parámetros get
            $id = Html::encode($_GET["id"]);
            $authKey = $_GET["authKey"];

            if ((int) $id) {
                //Realizamos la consulta para obtener el registro
                $model = $table
                        ->find()
                        ->where("id=:id", [":id" => $id])
                        ->andWhere("authKey=:authKey", [":authKey" => $authKey]);

                //Si el registro existe
                if ($model->count() == 1) {
                    $activar = Users::findOne($id);
                    $activar->activate = 1;
                    if ($activar->update()) {
                        echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; " . Url::toRoute("site/login") . "'>";
                    } else {
                        echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; " . Url::toRoute("site/login") . "'>";
                    }
                } else { //Si no existe redireccionamos a login
                    return $this->redirect(["site/login"]);
                }
            } else { //Si id no es un número entero redireccionamos a login
                return $this->redirect(["site/login"]);
            }
        }
    }

    public function actionRegister() {
        //Creamos la instancia con el model de validación
        $model = new FormRegister;

        //Mostrará un mensaje en la vista cuando el usuario se haya registrado
        $msg = null;

        //Validación mediante ajax
        if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }


        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                //Preparamos la consulta para guardar el usuario
                $table = new Users;
                $table->username = $model->username;
                $table->email = $model->email;
                //Encriptamos el password
                $table->password = crypt($model->password, Yii::$app->params["salt"]);
                //Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
                //clave será utilizada para activar el usuario
                $table->authKey = $this->randKey("abcdef0123456789", 200);
                //Creamos un token de acceso único para el usuario
                $table->accessToken = $this->randKey("abcdef0123456789", 200);

                //Si el registro es guardado correctamente
                if ($table->insert()) {
                    return $this->redirect(['login', 'model' => $model]);
                    //Nueva consulta para obtener el id del usuario
                    //Para confirmar al usuario se requiere su id y su authKey
                    $user = $table->find()->where(["email" => $model->email])->one();
                    $id = urlencode($user->id);
                    $authKey = urlencode($user->authKey);

                    $subject = "Confirmar registro";
                    $body = "<h1>Haga click en el siguiente enlace para finalizar tu registro</h1>";
                    $body .= "<a href='http://yii.local/index.php?r=site/confirm&id=" . $id . "&authKey=" . $authKey . "'>Confirmar</a>";

                    //Enviamos el correo
                    Yii::$app->mailer->compose()
                            ->setTo($user->email)
                            ->setFrom('rubengarana2000@gmail.com')
                            ->setSubject($subject)
                            ->setHtmlBody($body)
                            ->send();

                    $model->username = null;
                    $model->email = null;
                    $model->password = null;
                    $model->password_repeat = null;

                    $msg = "Enhorabuena, ahora sólo falta que confirmes tu registro en tu cuenta de correo";
                } else {
                    $msg = "Ha ocurrido un error al llevar a cabo tu registro";
                }
            } else {
                $model->getErrors();
            }
        }
        return $this->render("register", ["model" => $model, "msg" => $msg]);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout() {
        return $this->render('about');
    }

    public function beforeAction($action) {
        $exception = Yii::$app->getErrorHandler()->exception; // Manejo de excepciones
        if (parent::beforeAction($action)) { // Esto es requerido         
            if ($action->id == 'error') { // Si hay un error en la peticion
                if ($exception !== NULL) {
                    $this->layout = 'error'; // Cambia la plantilla 
                }
                return true;
            } else {
                return true;
            }
        }
    }

    public function actionCanton() {




        return $this->render('cantoncharge');
    }

    public function actionAprender() {




        return $this->render('aprender');
    }

    public function actionGarland() {




        return $this->render('garland');
    }

    public function actionOkoro() {




        return $this->render('okoro');
    }

    public function actionPick3() {




        return $this->render('pick3');
    }

    public function actionSummer() {




        return $this->render('summer');
    }

    public function actionKevin() {




        return $this->render('kevin');
    }

    public function actionCoinflip() {




        return $this->render('coinflip');
    }

    public function actionJarret() {




        return $this->render('jarret');
    }

    public function actionBestmoments() {




        return $this->render('bestmoments');
    }

    public function actionPublico() {




        return $this->render('publico');
    }
      public function actionMip() {




        return $this->render('mip');
    }
     public function actionLarry() {




        return $this->render('larry');
    }

}

views/site/cantoncharge.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

//Deberías cambiar el título
?>

<!DOCTYPE html>
<html lang="es">
    <head>

        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>

    <div class="container">
        <body>
            <article>

                <header>

                    <h1>El afiliado de los Cavs G-League se muda de Canton a Cleveland</h1>

                    <p class="publicacion">Publicado <time pubdate datetime="2014-03-28T20:00-04:00">2 meses atrás</time></p>
                    
                    <img src="../../web/img/chargegrande.jpg" alt="" style="
    width: 50%;
"/>
                </header>

                <p>Los Canton Charge ya no existen.            
                    En cambio, pasarán por el Cleveland Charge la próxima temporada, ya que la filial de Cleveland Cavaliers G-League comenzará a jugar en el centro de la ciudad la próxima temporada en el Wolstein Center de la Universidad Estatal de Cleveland. Recientemente se tomó la decisión de no extender su contrato de arrendamiento vencido en el Canton Memorial Civic Center, poniendo fin a una estadía de 10 años y nueve temporadas en el Civic Center, que sirvió como la primera sede del equipo después de que los Cavaliers adquirieran la franquicia. reubicado de Nuevo México y rebautizado como Canton Charge en 2011.
                </p>
                <br>

                <p>           
                    “Queremos agradecer al alcalde Bernabei, la ciudad de Canton y nuestros fanáticos y socios de Charge por una década de emoción en el Civic Center”, dijo el director ejecutivo de Rock Entertainment Group, Len Komoroski, en un comunicado. “Cuando adquirimos la franquicia y la trasladamos aquí al noreste de Ohio, nuestro objetivo era crear la mejor operación y experiencia en la G-League, tanto dentro como fuera de la cancha. Hemos tenido éxito trabajando hacia ambos objetivos y ese sigue siendo nuestro compromiso y enfoque ".               
                </p>  
                         <br>
                                  <br>
                <p>
                    The Charge jugó una campaña abreviada 2020-21 en Orlando, como parte de la G League Bubble. El último juego en Canton fue hace más de un año. El Charge se fue de 5-10 durante la temporada abreviada.          
                </p>
                         <br>
                                  <br>
                <p>
                    “Estoy, por supuesto, decepcionado de que el Charge ya no juegue en Canton. Tuvimos conversaciones abiertas y profesionales con la administración de Charge sobre cómo extender su contrato de arrendamiento y quedarse ”, declaró el alcalde de Cantón, Thomas Bernabei. “Sin embargo, su movimiento es estimulado por el deseo de estar mucho más cerca del centro de operaciones central de los Cavaliers. Trabajamos duro para mantenerlos aquí, pero aprecio su franqueza en nuestras conversaciones, respeto su decisión y sinceramente les deseo lo mejor. También apreciamos su compromiso continuo y la expansión de la programación y el apoyo para los jóvenes y la comunidad aquí. Les agradecemos por una carrera emocionante en el Civic Center y seguiremos siendo fanáticos del Charge y los Cavs ”.               
                </p>
                         <br>
                                  <br>
                <p>
                    El traslado al Wolstein Center de la Universidad Estatal de Cleveland (CSU) sigue una tendencia en la G League, donde los equipos continúan operando mucho más cerca de las sedes y los centros de entrenamiento de la franquicia de la NBA. Ejemplos recientes de esto están presentes en Washington y Detroit, y más de la mitad de los equipos de la G League ahora se encuentran a menos de 30 millas de los estadios de juego e instalaciones de entrenamiento y desarrollo de su club matriz de la NBA.                
                </p>
                         <br>
                                  <br>
                <p>
                    El papel y la importancia de la G League dentro del panorama de desarrollo de la NBA continúa expandiéndose, ya que cerca del 60% de los jugadores que ahora están en la NBA han jugado en la G League. Jugar en el centro de Cleveland logra un mayor nivel de integración, recursos y flexibilidad operativa para los jugadores de Charge, el personal y los miembros de la oficina principal según la ubicación se encuentra a varias cuadras de Rocket Mortgage FieldHouse y a solo ocho millas de Cleveland Clinic Courts, el entrenamiento y el jugador centro de desarrollo de los Cavaliers. The Charge ahora podrá ejercer tanto en Rocket Mortgage FieldHouse como en Cleveland Clinic Courts, así como utilizar las instalaciones extendidas y los beneficios de tratamiento presentes en ambos lugares.                
                </p>
                         <br>
                                  <br>
                <p>
                    “Estamos muy agradecidos por las temporadas que jugamos en el Civic Center en Canton. Disfrutamos de momentos realmente especiales allí con nuestros jugadores, personal y fanáticos por igual ”, agregó el gerente general de Charge, Brendon Yu. “Al mirar hacia el futuro, estamos muy contentos de poder continuar con el crecimiento de Charge en el Wolstein Center. La proximidad a Cleveland Clinic Courts y Rocket Mortgage Fieldhouse crea una sinergia mejorada entre los dos equipos y fomentará un desarrollo de personal aún mayor que será muy impactante para nosotros ".                
                </p>
                <p>
                    La transición para jugar en CSU también inicia una nueva era de baloncesto Charge en el centro de Cleveland y una que estará acompañada por el desarrollo de una visión a largo plazo y una asociación con CSU que también puede alinearse con la evolución de sus planes futuros de sedes.             
                </p>
                         <br>
                                  <br>
                <p>
                    The Charge también anunció un compromiso para expandir los deportes juveniles, la programación comunitaria y el apoyo en Canton, incluidos los programas de campamento y clínica de los Cavs Academy y Jr. Cavs y los juegos Cavs Elite para brindar múltiples oportunidades nuevas a la comunidad de Canton. Este compromiso ampliado también aumentará la cantidad de oportunidades gratuitas para que participen los jóvenes locales desatendidos o desfavorecidos. Las mayores oportunidades también serán parte de un compromiso mejorado para abordar la escasez de alimentos en la región a través de la donación de ganancias de eventos selectos de campamentos o torneos que la organización de los Cavs igualará para generar un mínimo de 20,000 comidas adicionales para los esfuerzos locales, incluido el Akron. -Canton Foodbank y Stark Hunger Task Force.
                </p>

              
            </article>

    </div>


</body>



</html>

views/site/coinflip.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

//Deberías cambiar el título
?>

<!DOCTYPE html>
<html lang="es">
    <head>

        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>

    <div class="container">
        <body>
            <article>

                <header>

                    <h1>CAVS PIERDE LA LOTERÍA Y TENDRÁ LA QUINTA PEOR PROBABILIDAD</h1>

                    <p class="publicacion">Publicado <time pubdate datetime="2014-03-28T20:00-04:00">2 meses atrás</time></p>
                    
                    <img src="../../web/img/draft_2.jpg" alt="" style="
    width: 60%;
"/>
                </header>

                <p>          
Los Cavs recibieron noticias desafortunadas sobre el draft el martes.

                </p>
                <br>

                <p>           
Según la NBA, los Cavs perdieron su lanzamiento de moneda con el Thunder para ver quién obtendría las probabilidades de la lotería del cuarto mejor draft y la quinta mejor. Debido a que los Cavs perdieron, tienen lo último. Aquí están sus probabilidades de draft completas:

                </p>  
                         <br>
                                  
                                  <div class="twitter-tweet twitter-tweet-rendered" style="display: flex; max-width: 550px; width: 100%; margin-top: 10px; margin-bottom: 10px;"><iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true" class="" style="position: static; visibility: visible; width: 550px; height: 659px; display: block; flex-grow: 1;" title="Tweet de Twitter" src="https://platform.twitter.com/embed/Tweet.html?dnt=false&amp;embedId=twitter-widget-0&amp;features=eyJ0ZndfZXhwZXJpbWVudHNfY29va2llX2V4cGlyYXRpb24iOnsiYnVja2V0IjoxMjA5NjAwLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2hvcml6b25fdHdlZXRfZW1iZWRfOTU1NSI6eyJidWNrZXQiOiJodGUiLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3R3ZWV0X2VtYmVkX2NsaWNrYWJpbGl0eV8xMjEwMiI6eyJidWNrZXQiOiJjb250cm9sIiwidmVyc2lvbiI6bnVsbH19&amp;frame=false&amp;hideCard=false&amp;hideThread=false&amp;id=1397252985319743488&amp;lang=en&amp;origin=https%3A%2F%2Fwww.fearthesword.com%2F2021%2F5%2F25%2F22454090%2Fcleveland-cavaliers-2021-draft-lottery-coin-toss&amp;sessionId=26a2adcb8c68189edef4b5e6ea739da78d4ef870&amp;siteScreenName=FearTheSword&amp;theme=light&amp;widgetsVersion=82e1070%3A1619632193066&amp;width=550px" data-tweet-id="1397252985319743488"></iframe></div>
                  <br>
                                  <p>
También es de destacar: Los Cavs ganaron lanzamientos de monedas de lotería y luego terminaron con una selección peor antes. Mire hacia atrás en 2012, cuando Cleveland ganó un lanzamiento de moneda con Nueva Orleans. Los Pelicans luego terminaron ganando la lotería para obtener a Anthony Davis y los Cavs eligieron cuarto y obtuvieron a Dion Waiters. Esto es realmente solo suerte al final del día.


                </p>
                         <br>
                                  <br>
                <p>
La Lotería del Draft de la NBA 2021 , también conocida como cuando es el momento de preocuparse realmente por las pelotas de ping pong, está programada para el 22 de junio.

                </p>
          

            </article>

    </div>


</body>



</html>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

//Deberías cambiar el título
$this->title = 'My Yii Application';
?>

<!DOCTYPE html>
<html lang="en">
    <head>

        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <?php
    if (!Yii::$app->user->isGuest) {
        ?>

        <body>

            <div id="bloque1" class="col-lg-4">
                <a href="jugadores/estadisticas">
                    <h1>JUGADORES</h1>
                </a>
                <a href="entrenadores/entrendadoresindex">
                    <h1>ENTRENADORES</h1>
                </a>
                <a href="partidos/resultados">
                    <h1>PARTIDOS</h1>
                </a>
            </div>

            <div  class="col-lg-4">
                <img id="logof" src="../web/img/logo.png" alt="logo"/>
            </div>

            <div id="bloque2" class="col-lg-4">
                <a href="realizan/entrenos">
                    <h1>ENTRENAMIENTOS</h1>
                </a>
                <a href="partidos/maximos">
                    <h1>ESTADÍSTICAS</h1>
                </a>
                <a href="contratos/contratos">
                    <h1>CONTRATOS</h1>
                </a>

            </div>


           

        </body>
        <?php
    } else {
        ?>
        <body>
            <div class="container">
                <div class="row">
                    <div id="noticias">
   <div id="loultimo"style="
    padding-left: 16px;
     padding-right: 10px;
">
                    <h1>LO ÚLTIMO</h1>
                </div>
                        <div  class="col-lg-6">
<a href="site/larry">    <?= Html::tag('div', Html::img('@web/img/imagenlarry.jpg', ['id' => 'noticia1'])); ?></a>
 <p class="ultimanoticia">Reseña de la temporada 2020-21 de Larry Nance Jr.
                        </div>
                        <div id="noticiassub">
                         
                            <div id="notas2"  class="col-lg-6">
                              
                                   <div class="card">
   <a href="site/canton">  <?= Html::tag('div', Html::img('@web/img/charge.jpg', ['id' => 'noticia2'])); ?> </a>
                                    <div class="card-body">
                                        <h5 class="card-title">Canton Charge</h5>
                                        <p class="card-text">El afiliado de los Cavs G-League se muda de Canton a Cleveland.
                                    </div>
                                </div>


                                <div class="card">
   <a href="site/aprender">   <?= Html::tag('div', Html::img('@web/img/imagen1.jpg', ['id' => 'noticia2'])); ?> </a>
                                    <div class="card-body">
                                        <h5 class="card-title">Cavaliers Team</h5>
                                        <p class="card-text">¿Qué hemos aprendido de los cavs esta temporada: 2020-21?</p>

                                    </div>
                                </div>


                                     <div class="card">
    <a href="site/garland">  <?= Html::tag('div', Html::img('@web/img/imagen4 .jpg', ['id' => 'noticia2'])); ?></a>
                                    <div class="card-body">
                                        <h5 class="card-title">Darius Garland</h5>
                                        <p class="card-text">Darius Garland se une al Team USA </p>

                                    </div>
                                </div>


                                    <div class="card">
    <a href="site/okoro">  <?= Html::tag('div', Html::img('@web/img/imagen8.jpg', ['id' => 'noticia2'])); ?></a>
                                    <div class="card-body">
                                        <h5 class="card-title">Isaac Okoro</h5>
                                        <p class="card-text">Isaac Okoro es nombrado en el segundo quinteto de Rookies </p>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="loultimo">
                    <h1>MÁS NOTICIAS</h1>
                </div>
                <div id="noticiasloultimo">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="card2">
   <a href="site/pick3">   <?= Html::tag('div', Html::img('@web/img/usman.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">CAVS ELEGIRÁ EN TERCER LUGAR EN EL NBA DRAFT2021 
                                </div>
                            </div>
                        </div>


                        <div class="col-lg-3">
                            <div class="card2">
   <a href="site/summer">   <?= Html::tag('div', Html::img('@web/img/summer.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">NBA Summer League REGRESA EN AGOSTO</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="card2">
  <a href="site/kevin">    <?= Html::tag('div', Html::img('@web/img/imagen20.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">Kevin Love JUGARá CON EL TEAM USA EN LOS JUEGOS OLÍMPICOS</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>


                        <div class="col-lg-3">
                            <div class="card2">
   <a href="site/coinflip">   <?= Html::tag('div', Html::img('@web/img/draft.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">CAVS PIERDE CONTRA LOS THUNDER EN LA LOTERÍA Y TENDRÁ LA QUINTA PEOR PROBABILIDAD</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="card2">
   <a href="site/jarret">   <?= Html::tag('div', Html::img('@web/img/imagen16.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">Los Cavs pueden sacar más provecho de Allen adoptando su potencial</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>


                        <div class="col-lg-3">
                            <div class="card2">
  <a href="site/bestmoments">    <?= Html::tag('div', Html::img('@web/img/imagen12.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">Roundtable: mejores momentos de los Cavs, momentos destacados y más</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="card2">
  <a href="site/mip">    <?= Html::tag('div', Html::img('@web/img/imagen5.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">NBA Reacts: ¿Quién merece ganar el premio al jugador más mejorado?</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>


                        <div class="col-lg-3">
                            <div class="card2">
   <a href="site/publico">   <?= Html::tag('div', Html::img('@web/img/imagen6.jpg', ['id' => 'noticia2'])); ?></a>
                                <div class="card-body">
                                    <h5 class="card-title">SB Nation Reacts: Impacto del público, playoff series y más</h5>
                                    <p class="card-text"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>





        </body>
    <?php
}
?>

</html>