models/Partidos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "partidos".
 *
 * @property int $cod_partido
 * @property int $puntos_rivales
 * @property string $nombre_rival
 * @property string|null $imagen
 * @property string $estadio
 * @property string $mes
 * @property string|null $fecha
 *
 * @property Juegan[] $juegans
 * @property Jugadores[] $codJugadors
 */
class Partidos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */public $puntos;
    public $TC;
    public $T3;
    public $TL;
    public $robos;
    public $nosotros;
    public $resultado;
    public  $codigo;
    public $media;
    public  $cod_jugador;
    public $minutos;
    public $video;
     public $fechames;

    public static function tableName()
    {
        return 'partidos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['puntos_rivales', 'nombre_rival', 'estadio', 'fecha'], 'required'],
            [['puntos_rivales'], 'integer'],
            [['fecha'], 'safe'],
            [['nombre_rival'], 'string', 'max' => 25],
            [['imagen'], 'string', 'max' => 500],
            [['estadio', 'mes'], 'string', 'max' => 255],
            [['video'], 'file', 'skipOnEmpty' => true, 'extensions' => 'jpg,mp3,mp4'],
            [['puntos_rivales'],'integer','max' => 200, 'min' => 0],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cod_partido' => 'Cod Partido',
            'puntos_rivales' => 'Puntos Rivales',
            'nombre_rival' => 'Nombre Rival',
            'imagen' => 'Imagen',
            'estadio' => 'Estadio',
            'mes' => 'Mes',
            'fecha' => 'Fecha',
        ];
    }

    /**
     * Gets query for [[Juegans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJuegans()
    {
        return $this->hasMany(Juegan::className(), ['cod_partido' => 'cod_partido']);
    }

    /**
     * Gets query for [[CodJugadors]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodJugadors()
    {
        return $this->hasMany(Jugadores::className(), ['cod_jugador' => 'cod_jugador'])->viaTable('juegan', ['cod_partido' => 'cod_partido']);
    }
}

controllers/PartidosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Partidos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Jugadores;
use app\models\Juegan;
use yii\web\UploadedFile;

/**
 * PartidosController implements the CRUD actions for Partidos model.
 */
class PartidosController extends Controller {

    public function actionResultados() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido'),
            'pagination' => false,
        ]);
        return $this->render("resultados", [
                    "resultados" => $dataProvider,
        ]);
    }
     public function actionResultadosuser() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido'),
            'pagination' => false,
        ]);
        return $this->render("resultadosuser", [
                    "resultados" => $dataProvider,
        ]);
    }
     public function actionPartido($cod) {
      
        return $this->render("partido", [
                    "cod" => $cod,
        ]);
    }
     public function actionPartidouser($cod) {
      
        return $this->render("partidouser", [
                    "cod" => $cod,
        ]);
    }
    
    public function actionResultadospormes($mes=null) {
        if($mes==null){
            $mes = date('m');
        }
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido')
                    ->where("month(partidos.fecha)=$mes"),
            
            'pagination' => false,
        ]);
        return $this->render("resultadosmes", [
                    "mes"=>$mes,
                    "resultados" => $dataProvider,
        ]);
    }
     public function actionResultadospormesuser($mes=null) {
        if($mes==null){
            $mes = date('m');
        }
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('partidos.cod_partido,partidos.nombre_rival,
        sum(juegan.puntos_jugador) nosotros,
        partidos.puntos_rivales,
        SUM(juegan.puntos_jugador)>partidos.puntos_rivales as resultado,
        mes,fecha,
        estadio')
                    ->innerJoin('juegan', 'juegan.cod_partido = partidos.cod_partido')
                    ->groupBy('juegan.cod_partido')
                    ->where("month(partidos.fecha)=$mes"),
            
            'pagination' => false,
        ]);
        return $this->render("resultadosmesuser", [
                    "mes"=>$mes,
                    "resultados" => $dataProvider,
        ]);
    }

    public function actionVistaindividual($cod) {
    
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Juegan::find()
                    ->select('
                    nombre,
                    cod_partido,
                    apellidos,
                    puntos_jugador,
                    rebotes_jugador,
                    asistencias_jugador,
                    robos,
                    minutos,
                    SUM(aciertos_jugador)/SUM(tiros_jugador)*100 AS TC,
                    SUM(t3_acertados)/SUM(t3_intentados)*100 T3,
                    SUM(minutos_jugador) minutos,
                    SUM(tl_acertados)/SUM(tl_intentados)*100 TL,
                    tapones')
                    ->innerJoin('jugadores', 'juegan.cod_jugador = jugadores.cod_jugador')
                    ->where('cod_partido='.$cod)
                    ->andWhere('puntos_jugador is not null')
                    ->groupBy('jugadores.cod_jugador'),
            'pagination' => false,
            'sort' => ['attributes' => ['nombre', 'apellidos', 'puntos_jugador', 'rebotes_jugador', 'asistencias_jugador','robos','minutos','TC', 'T3', 'TL','tapones']]
        ]);
        return $this->render("individuales", [
                    "resultados" => $dataProvider,
                     "cod"=>$cod
            
        ]);
    }
      public function actionVistaindividualuser($cod) {
    
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Juegan::find()
                    ->select('
                    nombre,
                    cod_partido,
                    apellidos,
                    puntos_jugador,
                    rebotes_jugador,
                    asistencias_jugador,
                    robos,
                    minutos,
                    SUM(aciertos_jugador)/SUM(tiros_jugador)*100 AS TC,
                    SUM(t3_acertados)/SUM(t3_intentados)*100 T3,
                    SUM(minutos_jugador) minutos,
                    SUM(tl_acertados)/SUM(tl_intentados)*100 TL,
                    tapones')
                    ->innerJoin('jugadores', 'juegan.cod_jugador = jugadores.cod_jugador')
                    ->where('cod_partido='.$cod)
                    ->andWhere('puntos_jugador is not null')
                    ->groupBy('jugadores.cod_jugador'),
            'pagination' => false,
            'sort' => ['attributes' => ['nombre', 'apellidos', 'puntos_jugador', 'rebotes_jugador', 'asistencias_jugador','robos','minutos','TC', 'T3', 'TL','tapones']]
        ]);
        return $this->render("individualesuser", [
                    "resultados" => $dataProvider,
                     "cod"=>$cod
            
        ]);
    }

    public function actionMaximos() {
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('month(fecha)fechames,nombre_rival,
                            SUM(j.puntos_jugador) AS puntos,
                            SUM(j.aciertos_jugador)/SUM(j.tiros_jugador)*100 AS TC,
                            SUM(j.t3_acertados)/SUM(j.t3_intentados)*100 AS T3,
                            SUM(j.tl_acertados)/SUM(j.tl_intentados)*100 AS TL')
                    ->innerJoin('juegan j', 'partidos.cod_partido=j.cod_partido')
                    ->groupBy('fechames'),
            'sort' => ['attributes' => ['fechames', 'puntos', 'TC', 'T3', 'TL']]
        ]);

        $dataProvider6 = new ActiveDataProvider([
            'query' => \app\models\Partidos::find()
                    ->select('month(fecha)fechames,nombre_rival,
                            SUM(j.puntos_jugador)puntos,
                            SUM(j.aciertos_jugador)/SUM(j.tiros_jugador)*100 AS TC,
                            SUM(j.t3_acertados)/SUM(j.t3_intentados)*100 AS T3,
                            SUM(j.tl_acertados)/SUM(j.tl_intentados)*100 AS TL')
                    ->innerJoin('juegan j', 'partidos.cod_partido=j.cod_partido')
                    ->groupBy('nombre_rival'),
            'pagination' => false,
            'sort' => ['attributes' => ['nombre_rival', 'puntos', 'TC', 'T3', 'TL']]
        ]);

        return $this->render("globales", [
                    "resultados" => $dataProvider,
                    "resultados6" => $dataProvider6,
//                    "resultados9" => $dataProvider9,
        ]);
    }
 

    public function actionLideres() {
        $dataProvider2 = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,
                            avg(puntos_jugador) puntos')
                    ->innerJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('jugadores.estado=1')
                    ->groupBy('jugadores.cod_jugador')
                    ->orderBy(['puntos' => SORT_DESC])
                    ->limit(1),
            'pagination' => false
        ]);
        $dataProvider3 = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,
                            avg(rebotes_jugador) rebotes')
                    ->innerJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('jugadores.estado=1')
                    ->groupBy('jugadores.cod_jugador')
                    ->orderBy(['rebotes' => SORT_DESC])
                    ->limit(1),
            'pagination' => false
        ]);
        $dataProvider4 = new ActiveDataProvider([
            'query' => \app\models\Jugadores::find()
                    ->select('nombre,apellidos,
                            avg(asistencias_jugador) asistencias')
                    ->innerJoin('juegan j', 'jugadores.cod_jugador=j.cod_jugador')
                    ->where('jugadores.estado=1')
                    ->groupBy('jugadores.cod_jugador')
                    ->orderBy(['asistencias' => SORT_DESC])
                    ->limit(1),
            'pagination' => false
        ]);

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\widgets\Alert;


/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
     public function actionUsersindex() {
        $dataProvider = new ActiveDataProvider([
        'query' => \app\models\Users::find()
        ->select('id,username,admin')


        ]);
        return $this->render("usersindex", [
                    "resultados" => $dataProvider,
        ]);
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Users::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['usersindex']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
     public function actionPrivilegios($id) {
        $model = $this->findModel($id);


        if ($model->admin == 1) {
            $model->admin=0;
            $model->save();
   
            return $this->redirect(['users/usersindex']);
            
        } else {
            $model->admin = 1;
            $model->save(false);
            return $this->redirect(['users/usersindex']);
        }
    }

}

views/partidos/_globales.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


<h1>Puntos por partido</h1>
<div class="row">
<div class="col-lg-6">
   <ul>
  <li id="titulolista">
        <?php
 
echo floor($model->puntos*100)/100;
 
    ?>
  </li>
  <li>Collin Sexton</li>
  <li>2020-2021 Temporada Regular</li>
 
</ul>
</div>

  
 <div class="col-lg-6">
    <?php
 

//   PARA COGER EL CODIGO DE CADA JUGADOR Y ASI COGER SU IMAGEN
    echo Html::img('@web/img/'.$model['nombre'].'2.png');
 
    ?>
       
<!--       PARA PASAR A LA ACCION JUEGAN/CREATE EL COD_JUGADOR Y EL COD DEL PARTIDO ESPECIFICO-->
     
        </div>
    </div>

    



</div>
  
 <?php

    

?>

views/partidos/_globales2.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1>Rebotes por partido</h1>
<div class="row">
<div class="col-lg-6">
   <ul>
  <li id="titulolista">
        <?php
 
echo floor($model->rebotes*100)/100;
 
    ?>
  </li>
  <li>
        <?php
 
echo $model->nombre.' '.$model->apellidos;
 
    ?>
       
  </li>
  <li>2020-2021 Temporada Regular</li>
 
</ul>
</div>
<div class="col-lg-6">

    <?php
 

//   PARA COGER EL CODIGO DE CADA JUGADOR Y ASI COGER SU IMAGEN
     echo Html::img('@web/img/'.$model['nombre'].'2.png');
 
    ?>
       
                 
        
<!--       PARA PASAR A LA ACCION JUEGAN/CREATE EL COD_JUGADOR Y EL COD DEL PARTIDO ESPECIFICO-->
           
 
    </div>

    
    
    
    

</div> 
</div>
 <?php

    

?>

views/partidos/_globales3.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<h1>asistencias por partido</h1>
<div class="row">
<div class="col-lg-6">
   <ul>
  <li id="titulolista"> 
        <?php
 
echo floor($model->asistencias*100)/100;
 
    ?>
  </li>
  <li>        <?php
 
echo $model->nombre.' '.$model->apellidos;
 
    ?>
       </li>
  <li>2020-2021 Temporada Regular</li>
 
</ul>
</div>

  
 <div class="col-lg-6">
 <?php
 

//   PARA COGER EL CODIGO DE CADA JUGADOR Y ASI COGER SU IMAGEN
    echo Html::img('@web/img/'.$model['nombre'].'2.png');
 
    ?>
<!--       PARA PASAR A LA ACCION JUEGAN/CREATE EL COD_JUGADOR Y EL COD DEL PARTIDO ESPECIFICO-->
     
        </div>
    </div>

    



</div>
  
 <?php

    

?>

views/partidos/_globales4.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Juegan */

$this->title = 'Create Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<h1>robos por partido</h1>
<div class="row">
<div class="col-lg-6">
   <ul>
  <li id="titulolista"> 
         <?php
 
echo floor($model->robos*100)/100;
 
    ?>
      
  </li>
  <li>        <?php
 
echo $model->nombre.' '.$model->apellidos;
 
    ?>
       </li>
  <li>2020-2021 Temporada Regular</li>
 
</ul>
</div>

  
 <div class="col-lg-6">
   <?php
 

//   PARA COGER EL CODIGO DE CADA JUGADOR Y ASI COGER SU IMAGEN
  echo Html::img('@web/img/'.$model['nombre'].'2.png');
 
    ?>
       
<!--       PARA PASAR A LA ACCION JUEGAN/CREATE EL COD_JUGADOR Y EL COD DEL PARTIDO ESPECIFICO-->
     
        </div>
    </div>

    



</div>
  
 <?php

    

?>

views/partidos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PartidosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="partidos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'cod_partido') ?>

    <?= $form->field($model, 'puntos_rivales') ?>

    <?= $form->field($model, 'nombre_rival') ?>

    <?= $form->field($model, 'imagen') ?>

    <?= $form->field($model, 'estadio') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/partidos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Partidos */

$this->title = 'Create Partidos';
$this->params['breadcrumbs'][] = ['label' => 'Partidos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="partidos-create">

    <h1></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'codigo'=>$model->cod_partido,
      
    ]) ?>

</div>

views/partidos/resultadosmesuser.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\DataColumn;
use yii\helpers\Url;
use aryelds\sweetalert\SweetAlert;
use kartik\export\ExportMenu;

$js = <<< JS

 krajeeDialog.confirm = function (message, callback) {
    swal({

title: message,
text: "Esta acción será definitiva",
type: "warning",
showCancelButton: true,
confirmButtonColor: "#5f022a",
confirmButtonText: "Borrar",
cancelButtonText: "Cancelar",
closeOnConfirm: false,
closeOnCancel: true,
        title: message,
        type: "warning",
        showCancelButton: true,
        closeOnConfirm: true,
        allowOutsideClick: true
    }, callback);
}
JS;
$this->registerJs($js, yii\web\view::POS_READY);
$this->title = 'PARTIDOS';
$this->params['breadcrumbs'][] = $this->title;
?>
<script src="../js/jquery.js"></script>
<div class="jugadores-index">
    <div class="container">
        <?php
        $resta=1;
        $suma=1;
        $mestitulo;
       switch ($mes) {
                                    case '1' :
                                        $mestitulo='enero';
                                        $resta=-11;
                                        break;
                                    case '2' :
                                         $mestitulo='febrero';
                                        break;
                                    case '3' :
                                         $mestitulo='marzo';
                                        break;
                                    case '4' :
                                         $mestitulo='abril';
                                        break;
                                    case '5' :
                                         $mestitulo='mayo';
                                        break;
                                    case '6' :
                                         $mestitulo='junio';
                                        break;
                                    case '7' :
                                         $mestitulo='julio';
                                        break;
                                    case '8' :
                                         $mestitulo='agosto';
                                        break;
                                    case '9' :
                                         $mestitulo='septiembre';
                                        break;
                                    case '10' :
                                         $mestitulo='octubre';
                                        break;
                                    case '11' :
                                         $mestitulo='noviembre';
                                        break;
                                    case '12' :
                                         $mestitulo='diciembre';
                                        $suma=-11;
                                        break;
      
}?>
            <h1 id="titulonoadmincalendaruser">
<?= Html::a('<', ['resultadospormesuser', 'mes' => $mes - $resta], ['class' => 'btn',"id"=>"bajar"]) ?><?= Html::encode($mestitulo) ?><?= Html::a('>', ['resultadospormesuser', 'mes' => $mes + $suma], ['class' => 'btn',"id"=>"subir"]) ?></h1>




            <?=
            GridView::widget([
                'dataProvider' => $resultados,
                //usamos esto para poder concatenar las columnas.
                'columns' => [
                    'resultado',
                    [
                        'label' => 'puntos',
                        'value' => function ($model) {
                            return $model->nosotros . '-' . $model->puntos_rivales;
                        }
                    ],
                    [
                        'attribute' => 'nombre_rival',
                        'value' => function ($model) {
                            return Html::a($model->nombre_rival, ['partidos/vistaindividual', 'cod' => $model->cod_partido]);
                        },
                        'format' => 'raw',
                    ],
                    [
                        'label' => 'estadio',
                        'value' => function ($model) {
                            switch ($model->estadio) {
                                case 'Atlanta Hawks' :
                                    return 'State Farm Arena';
                                    break;
                                case 'Boston Celtics' :
                                    return 'TD Garden';
                                    break;
                                case 'Brooklyn Nets' :
                                    return 'Barclays Center';
                                    break;
                                case 'Charlotte Hornets' :
                                    return 'Spectrum Center';
                                    break;
                                case 'Chicago Bulls' :
                                    return 'United Center';
                                    break;
                                case 'Dallas Mavericks' :
                                    return 'American Airlines Center';
                                    break;
                                case 'Denver Nuggets' :
                                    return 'Pepsi Center';
                                    break;
                                case 'Detroit Pistons' :
                                    return 'Little Caesars Arena';
                                    break;
                                case 'Golden State Warriors' :
                                    return 'Chase Center';
                                    break;
                                case 'Houston Rockets' :
                                    return 'Toyota Center';
                                    break;
                                case 'Indiana Pacers' :
                                    return 'Bankers Life Fieldhouse';
                                    break;
                                case 'Los Angeles Clippers' :
                                    return 'Staples Center';
                                    break;
                                case 'Los Angeles Lakers' :
                                    return 'Staples Center';
                                    break;
                                case 'Memphis Grizzlies' :
                                    return 'FedEx Forum';
                                    break;
                                case 'Miami Heat' :
                                    return 'American Airlines Arena';
                                    break;
                                case 'Milwaukee Bucks' :
                                    return 'Fiserv Forum';
                                    break;
                                case 'Minnesota Timberwolves' :
                                    return 'Target Center';
                                    break;
                                case 'New Orleans Pelicans' :
                                    return 'Smoothie King Center';
                                    break;
                                case 'New York Knicks' :
                                    return 'Madison Square Garden';
                                    break;
                                case 'Oklahoma City Thunder' :
                                    return 'Chesapeake Energy Arena';
                                    break;
                                case 'Orlando Magic' :
                                    return 'Amway Center';
                                    break;
                                case 'Philadelphia 76ers' :
                                    return 'Wells Fargo Center';
                                    break;
                                case 'Phoenix Suns' :
                                    return 'Talking Stick Resort Arena';
                                    break;
                                case 'Portland Trail Blazers' :
                                    return 'Moda Center';
                                    break;
                                case 'Sacramento Kings' :
                                    return 'Golden 1 Center';
                                    break;
                                case 'San Antonio Spurs' :
                                    return 'AT&T Center';
                                    break;
                                case 'Toronto Raptors' :
                                    return 'Scotiabank Arena';
                                    break;
                                case 'Utah Jazz' :
                                    return 'Vivint Smart Home Arena';
                                    break;
                                case 'Washington Wizards' :
                                    return 'Capital One Arena';
                                    break;
                                default:
                                    return 'Rocket Mortage FieldHouse';
                            }
                        }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'contentOptions' => ['style' => 'width:80px;'],
                        'template' => '{view}',
                        'buttons' => [
                            'view' => function ($url, $model) {
                                $url = Url::to(['partidos/vistaindividualuser', 'cod' => $model->cod_partido]);
                                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => 'ver estadisticas individuales']);
                            },
                        ],
                    ],
                ],
            ]);
        
        ?>


    </div>

</div>


<script>

    $("table td:first-child").each(function () {
        var texto = $(this).text();
        if (texto == 1) {

            $(this).text('VICTORIA').css('color', 'green');
        }
        if (texto == 0) {
            $(this).text('DERROTA').css('color', 'red')
        }




    });
</script>